### ISSUE TITLE
Got Killed: 9 on iOS 11.3.1

### ISSUE THREAD

**Issue by linhmui** [abit-me/dumpexec#2]
Dear
I Got Killed: 9 on iOS 11.3.1 when run dumpexec with the lastest build. Please fix

Thanks

**Comment by abit-me** [comment]
Can you show me the log？

**Comment by linhmui** [comment]
@abit-me here is the log

iPhone:/var/mobile root# dumpexec              
Killed: 9                                      
iPhone:/var/mobile root#

**Comment by abit-me** [comment]
I seems a codesign error, have a try of ldid-S /usr/bin/dumpexec

**Comment by linhmui** [comment]
@abit-me please check log when run ldid or i made somethings wrong? Can you send me your .deb build, which working on your device. Thanks

Phone:~ root# dpkg -i dumpexec.deb            
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 996 package 'vn.gsm.filza64bit':  
 missing maintainer                            
Selecting previously unselected package dumpexec.                                              
(Reading database ... 3354 files and directories currently installed.)                         
Preparing to unpack dumpexec.deb ...           
Unpacking dumpexec (0.0.1) ...                 
Setting up dumpexec (0.0.1) ...                
iPhone:~ root# ldid -S ./usr/bin/dumpexec      
./minimal/mapping.h(54): _assert(false); errno=2                                               
iPhone:~ root# dumpexec                        
Killed: 9                                      
iPhone:~ root#

**Comment by abit-me** [comment]
the right command is
ldid -S /usr/bin/dumpexec
but you are
ldid -S ./usr/bin/dumpexec

**Comment by linhmui** [comment]
@abit-me still got killed:9 after run ldid -S
                                            
iPhone:/var/mobile root# ldid -S /usr/bin/dumpexec                                             
iPhone:/var/mobile root# dumpexec              
Killed: 9                                      
iPhone:/var/mobile root#

**Comment by linhmui** [comment]
@abit-me It worked after sign again using jtool, but when check Binary after Decrypt, it still Encrypted. Please check log:

Choose one: 25

[INFO] Copying ...
[INFO] Wait for child process to end
[INFO] Child process end status 9

[INFO] Zipping ...

[INFO] Create ipa at: /var/root/Documents/Decrypt/terrorist.war.game2018/game2018.ipa
iPhone:/var/mobile/Downloads root# otool -l /var/root/Documents/Decrypt/terrorist.war.game2018/Payload/game2018.app/game2018 | grep crypt
/var/root/Documents/Decrypt/terrorist.war.game2018/Payload/game2018.app/game2018:
     cryptoff 16384
    cryptsize 20905984
      cryptid 1
iPhone:/var/mobile/Downloads root#

**Comment by linhmui** [comment]
@abit-me It worked after sign again using jtool, but when check Binary after Decrypt, it still Encrypted. Please check log:

Choose one: 25

[INFO] Copying ...
[INFO] Wait for child process to end
[INFO] Child process end status 9

[INFO] Zipping ...

[INFO] Create ipa at: /var/root/Documents/Decrypt/com.facebook.Facebook/Facebook.ipa
iPhone:/var/mobile/Downloads root# otool -l /var/root/Documents/Decrypt/com.facebook.Facebook/Payload/Facebook.app/Facebook| grep crypt
/var/root/Documents/Decrypt/com.facebook.Facebook/Payload/Facebook.app/Facebook:
cryptoff 16384
cryptsize 20905984
cryptid 1
iPhone:/var/mobile/Downloads root#

**Comment by abit-me** [comment]
You should codesign both of them
/usr/lib/dumpdecrypted.dylib 
/usr/bin/dumpexec

**Comment by abit-me** [comment]
dumpexec will fork a child process to execute 'Your App', the log shows that child process exit 9, It seems child process was killed by kernel because of codesign error

**Comment by linhmui** [comment]
@abit-me Sorry about stupid question, but how can i sign dumpdecrypted.dylib? Because in iOS 11 when using:
 ldid -S /usr/lib/dumpdecrypted.dylib
ldid - S /usr/bin/dumpexec

it does not work (no thing happend when using these command). I signed dumpexec with jtool after make thin binary but with  dumpdecrypted.dylib i don't know how to do that

Thanks

**Comment by abit-me** [comment]
I don't have experience on iOS 11.x but codesign for dylib file  is same with executable file

**Comment by abit-me** [comment]
iOS 11 and iOS 12 support now

**Comment by bamtan** [comment]
\-

**Comment by Nosskirneh** [comment]
I'm getting Killed: 9 from `dumpdecrypted.dylib` too (running iOS 12.1.1).

```
A-iP6:~ root# ldid -Sent.plist /usr/lib/dumpdecrypted.dylib
A-iP6:~ root# DYLD_INSERT_LIBRARIES=/usr/lib/dumpdecrypted.dylib /var/containers/Bundle/Application/22770D54-F68E-4A82-8025-25557A9B5B17/Musi.app/Musi
Killed: 9
```

Seems to be a codesign issue, but I'm not sure how to solve them. Thanks for the help!

**Comment by bamtan** [comment]
@Nosskirneh A user from Reddit managed to get it working on A12/iOS 12.X through a bash script seen here: http://uar.no/scripts/dumpexec.sh 

(the thread https://www.reddit.com/r/jailbreakdevelopers/comments/bfpuhb/tutorial_dumpexec_working_for_a12_check_update_11/)
