### ISSUE TITLE
commit 说加了ios 12支持，但MD说仅支持ios 10

### ISSUE THREAD

**Issue by laoyur** [abit-me/dumpexec#3]
到底是啥情况啊
我手头没有ios 10的机器，自己测试了11、12，都是没法成功的，生成的二进制文件拖入ida依旧提示是加密的

**Comment by abit-me** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，因为iOS11和iOS12的插入动态库机制不能用了，所以目前不支持iOS11-iOS12的脱壳，您可以使用CrackerXI
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                a
                            
                    
                        
                            
                                    a@abit.me
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年06月26日 18:07，laoyur<notifications@github.com> 写道： 


到底是啥情况啊

我手头没有ios 10的机器，自己测试了11、12，都是没法成功的，生成的二进制文件拖入ida依旧提示是加密的



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
